import type { LinkItem } from './types';

export const links: LinkItem[] = [
	{
		id: 'asumi-game',
		title: { 'pt-BR': 'Asumi — O Jogo', en: 'Asumi — The Game' },
		description: {
			'pt-BR': 'Conheça nosso jogo principal',
			en: 'Check out our flagship game',
		},
		url: '/projects/asumi',
		iconName: 'gamepad',
		featured: true,
		category: 'game',
		scope: 'studio',
	},
	{
		id: 'newsletter',
		title: { 'pt-BR': 'Newsletter (Bugsletter)', en: 'Newsletter (Bugsletter)' },
		description: {
			'pt-BR': 'Novidades do estúdio direto no seu e-mail',
			en: 'Studio updates straight to your inbox',
		},
		url: '/bugsletter',
		iconName: 'newsletter',
		category: 'newsletter',
		scope: 'both',
	},
	{
		id: 'discord',
		title: { 'pt-BR': 'Discord', en: 'Discord' },
		description: {
			'pt-BR': 'Entre na nossa comunidade',
			en: 'Join our community',
		},
		url: 'https://go.madeinbugs.com.br/links-discord',
		iconName: 'discord',
		category: 'community',
		scope: 'both',
	},
	{
		id: 'instagram-mib',
		title: { 'pt-BR': 'Instagram', en: 'Instagram' },
		url: 'https://go.madeinbugs.com.br/links-instagram-mib',
		iconName: 'instagram',
		category: 'social',
		scope: 'studio',
	},
	{
		id: 'instagram-asumi',
		title: { 'pt-BR': 'Instagram do Asumi', en: 'Asumi Instagram' },
		url: 'https://go.madeinbugs.com.br/asumipage-instagram',
		iconName: 'instagram',
		featured: true,
		category: 'social',
		scope: 'asumi',
	},
	{
		id: 'tiktok-mib',
		title: { 'pt-BR': 'TikTok', en: 'TikTok' },
		url: 'https://go.madeinbugs.com.br/links-tiktok-mib',
		iconName: 'tiktok',
		category: 'social',
		scope: 'studio',
	},
	{
		id: 'tiktok-asumi',
		title: { 'pt-BR': 'TikTok do Asumi', en: 'Asumi TikTok' },
		url: 'https://go.madeinbugs.com.br/asumipage-tiktok',
		iconName: 'tiktok',
		category: 'social',
		scope: 'asumi',
	},
	{
		id: 'youtube-asumi',
		title: { 'pt-BR': 'YouTube', en: 'YouTube' },
		url: 'https://go.madeinbugs.com.br/asumipage-youtube',
		iconName: 'youtube',
		category: 'social',
		scope: 'asumi',
	},
	{
		id: 'youtube-mib',
		title: { 'pt-BR': 'YouTube', en: 'YouTube' },
		url: 'https://go.madeinbugs.com.br/links-youtube-mib',
		iconName: 'youtube',
		category: 'social',
		scope: 'studio',
	},
	{
		id: 'bluesky-mib',
		title: { 'pt-BR': 'Bluesky', en: 'Bluesky' },
		url: 'https://go.madeinbugs.com.br/links-bluesky-mib',
		iconName: 'bluesky',
		category: 'social',
		scope: 'studio',
	},
	{
		id: 'x-mib',
		title: { 'pt-BR': 'X / Twitter', en: 'X / Twitter' },
		url: 'https://go.madeinbugs.com.br/links-x-mib',
		iconName: 'x',
		category: 'social',
		scope: 'studio',
	},
	{
		id: 'site',
		title: { 'pt-BR': 'Site do estúdio', en: 'Studio website' },
		url: '/',
		iconName: 'globe',
		category: 'other',
		scope: 'asumi',
	},
];
